version: 2
jobs:
  build:
    working_directory: ~/YourMechanic/postgres_utility
    parallelism: 1
    shell: /bin/bash --login

    environment:
      CIRCLE_ARTIFACTS: /tmp/circleci-artifacts
      CIRCLE_TEST_REPORTS: /tmp/circleci-test-results
    docker:
      - image: circleci/ruby:2.6.2
        environment:
          RAILS_ENV: test
          PGHOST: 127.0.0.1
          PGUSER: postgres
      - image: circleci/postgres:9.5.15
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: postgres
    steps:
      - checkout
      - run: mkdir -p $CIRCLE_ARTIFACTS $CIRCLE_TEST_REPORTS      
      - restore_cache:
          keys:
          # This branch if available
          - v2-dep-{{ .Branch }}-
          # Default branch if not
          - v2-dep-master-
          # Any branch if there are none on the default branch - this should be unnecessary if you have your default branch configured correctly
          - v2-dep-
      - run:
          name: Install bundler for postgres_utility
          working_directory: ~/YourMechanic/postgres_utility
          command: gem install bundler:2.2.11
      - run:
          name: Install Gems for postgres_utility
          working_directory: ~/YourMechanic/postgres_utility
          command: bundle install
      # Save dependency cache
      - save_cache:
          key: v2-dep-{{ .Branch }}-{{ epoch }}
          paths:
          - vendor/bundle
          - ~/virtualenvs
          - ~/.m2
          - ~/.ivy2
          - ~/.bundle
      - run: sudo apt-get update && sudo apt-get install postgresql 9.5 && sudo apt-get install nodejs
      - run: createuser -s postgres
      - run:
          working_directory: ~/YourMechanic/postgres_utility
          command: bundle exec rubocop
      - run:
          working_directory: ~/YourMechanic/postgres_utility
          command: bundle exec rspec --colour --drb --profile -fd --format progress $(circleci tests glob "spec/*_spec.rb" | circleci tests split)
      - store_test_results:
          path: /tmp/circleci-test-results
      - store_artifacts:
          path: /tmp/circleci-artifacts
      - store_artifacts:
          path: /tmp/circleci-test-results
      - store_artifacts:
          path: postgres_utility/coverage